### ISSUE TITLE
Feature Request: Ability to collapse addons grouped with dependencies

### ISSUE THREAD

**Issue by Rycia** [Eliote/SimpleAddonManager#10]
By default, when you open the addon manager, all of the addons with dependencies, as so, are automatically open;

![image](https://user-images.githubusercontent.com/43384589/202598691-b06a19eb-6099-48e3-80a5-8997524b7df4.png)

There should be a toggle to collapse/uncollapse everything instead of everything being done so individually. Addon Control Panel is an addon that has this feature.

Additionally, an option should be added to automatically load Simple Addon Manager's UI when opened with everything already collapsed, for people like me who hate opening their addon list to see everything expanded out by default.

**Comment by Eliote** [comment]
It should actually remember the collapse state. But for sure an option to collapse/expand everything would be nice. :)
