### ISSUE TITLE
Support for nested profiles

### ISSUE THREAD

**Issue by Eliote** [Eliote/SimpleAddonManager#12]
Yeah, I already wanted to suggest the same.

[BetterAddonList](https://www.curseforge.com/wow/addons/betteraddonlist) lets you build nested sets. I really like the neat features of SimpleAddonManager, but without nested sets, honestly, I will probably never use it.

Let me explain why:

In BetterAddonList, the addon tree for my 20 toons looks _roughly_ like this:

```text
                  Base Set for all
                        |       \
                        |        \  
                        |       Some specialized sets
                        |              …
                  Base Set for 
                  Normal and Support
                   /           \
                  /             \
              Resting Set    Banker Set
                |               |
              Light Set      AH toon Set
                |
             Standard Set
                |        \
              Full Set    \
                           \
                         PvP Set
```

As the tree design suggests, these sets are nested: the child sets, lower in the tree, contain all addons of the parent sets they are connected to.

***

_Some examples:_ 

The _Base Set_ contains such basic addons like TinyPad, M6, OPie. The _Base Set for Normal and Support_ contains addons that are needed for all sets, except for the specialized sets (eg WeakAuras, ArkInventory, Bazooka, Leatrix, etc.).

There it branches out to _Normal_ (normal toons) and _Support_ (bankers and AH toons), both based on the _Base Set for Normal and Support_. 

The _Resting Set_ contains addons needed for a normal toon's everyday indoor life (crafting addons, VenturePlan, BrokerAnything, WQAchievements, but also pet battle stuff, etc.). An AH toon doesn't need that stuff.

Based on that, the _Light Set_ is for quick excursions, like killing a rare or two, or a quick Utgarde Pinaccle run for the (damn) mount, therefore it has addons like SilverDragon and Rarity.

_Standard Set_ is for, well, standard stuff like instances or extended world-questing, with addons like Raven, Hekili, TomTom, etc. The _Full Set_  is almost identical but has heavy-weights like Grail/Wholly and is meant for example for doing old questlines for achievements or legendaries and such.

An example for the (only semi-nested) _specialized sets_ is a "Mission table only" set, for non-crafting toons, that has only VenturePlan (plus the _Base Set for All_, but not the stuff  from _Base Set for Normal and Support_). Or a Torghast set with some specific addons that are useless for anything else.

***

The main reason for having different addon sets is loading time. My _Standard_ set takes 25-35 seconds to load. When I login just for the mission table, or the AH, I want a short loading screen, hence the smaller sets.

Another reason is technical issues. For example, TSM is notoriously buggy and tends to conflict with other addons, so I would never want to use that on any toon except the AH toons. 

The third reason is – and now we come to the point – that with _nested_ sets I can realize all that without much work:) The tree might look complicated, but it isn't.

If an addon manager does _not_ have nested sets, I would have to create each set as standalone set, and the maintenance of the sets would be very time-intensive:

Especially in transition phases between xpacs, like now, I often have to replace a non-working addon by a similar one, until it gets fixed, and then activate the old one again. _Without nested sets, I would have to do that for each and every set where the addon is contained._ With nested sets, I replace the addon once, in the set where it is contained, and then it gets inherited by the child sets. Simple.

Of course, if you have just 3 toons and a banker, you can probably live with two sets, or even use the Blizz addon manager, but once you have half an army of toons, differentiated – and nested! – sets are a huge help. 

– Tom

_Originally posted by @tflo in https://github.com/Eliote/SimpleAddonManager/issues/9#issuecomment-1324539649_

**Comment by tflo** [comment]
Thanks for moving.

**Comment by Eliote** [comment]
Done in: 9295fcb9df30cbf68be8ca88a34daf2c11e10fd0

**Comment by tflo** [comment]
Sorry, I had completely missed your 1.16 update 4 days ago.

Test-wise, I have transferred now all my sets and nestings from the BetterAddonList SV to SAM's SV table, and… it looks pretty damn good :)

Guess, I'll do the move :)

The way how I can manage the sets and nested sets in SAM is so much better than in BAL, namely the `Save (*)` function is a game changer!
With BAL, I configured my sets with the text editor directly in the SV file (and locked it afterwards), because it was simply too clunky to do that in the GUI.[^1] With SAM it seems feasible to do this in the GUI again!

Many thanks for adopting my suggestion, and above all for the intelligent implementation!

[^1]: With BAL it is impossible to save a change to a set while ignoring the nested sets. You have to disconnect all nested sets, then do your change/save, then reconnect all nested sets (Unless I was missing something…).
