### ISSUE TITLE
Profile.lua:21: bad argument #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by Ookami313** [Eliote/SimpleAddonManager#14]
Decided to give SAM a try. Installed 1.16 and when I logged in to the game I received the following error. Thanks.

1x SimpleAddonManager/Profile.lua:21: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@SimpleAddonManager/Profile.lua"]:21: in function <SimpleAddonManager/Profile.lua:10>
[string "@SimpleAddonManager/Profile.lua"]:333: in function `OnLoad'
[string "@SimpleAddonManager/Core.lua"]:360: in function `?'
[string "@SimpleAddonManager/Core.lua"]:328: in function <SimpleAddonManager/Core.lua:327>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by Eliote** [comment]
Can you try the version 1.17 and see if that fix it?

Thanks!

**Comment by Ookami313** [comment]
Looks good, no errors when I logged it this time. Thanks for the fix.
