### ISSUE TITLE
Feature request : Elvui skin

### ISSUE THREAD

**Issue by Araldwenn** [Eliote/SimpleAddonManager#15]
Hi,
I made the same suggestion on AddonSkin project page, would it be possible to make SAM skinned like Elvui ?

Thanks

**Comment by Eliote** [comment]
Hello,
If that project can skin SAM, I'm fine with it, but it's not something I aim for. Maintaining the main UI is already painful enough for me. :p
I'm also fine accepting pull request if any adjustment is needed to support it.

Thanks.

**Comment by raptormama** [comment]
The ElvUI plugin WindTools offers a skin for Simple Addon Manager. It's available [here on Github](https://github.com/fang2hou/ElvUI_WindTools).

**Comment by Eliote** [comment]
I'll assume that resolves this issue.
