### ISSUE TITLE
Improvements with dialog boxes

### ISSUE THREAD

**Issue by tflo** [Eliote/SimpleAddonManager#18]
### Dialog boxes and Return key:

The **text entry box** (e.g. when creating a new category) is ignoring the Return keystroke (Enter doesn't work either).

What I expected was that Return (and optionally Enter) works as confirmation, i.e. the same as clicking the OK button with the mouse.

(I'm on a Mac, so there is a slight chance that this is a Mac-specific issue.)

Similar for **non-text dialog boxes** (like the confirmations for saving), though here I don't know if it is intentional or not, as many addons do ignore the Return key for non-text dialogs. (Escape though works.)

### Confirmation dialogs when loading sets:

The confirmation dialog when _saving_ a set ('profile') is a very good thing, but I think it isn't really necessary when loading a set. Especially since you explicitly display the set name in the save dialog box (which is also a very good thing). So, if I accidentally load the wrong set, make changes, then I will see in the save dialog box that I had changed the wrong set.

– Tom

**Comment by Eliote** [comment]
Escape should now close the dialog. (only if the negative button doesn't do anything)
Enter should now confirm the dialog. (only when there's only one positive option)

**Comment by tflo** [comment]
Thank you!
