### ISSUE TITLE
'Show Blizzard addons found in dependencies' can have unintended consequences

### ISSUE THREAD

**Issue by tflo** [Eliote/SimpleAddonManager#21]
For informational purposes, 'Show Blizzard addons found in dependencies' is an interesting option. However it comes with a pitfall:

If you have this option enabled and then click 'Disable All' (e.g. if you want to remove all entries from a set), SAM will also disable all displayed Blizz addons, like here for example:

<img width="406" alt="WoWScrnShot_120922_172100" src="https://user-images.githubusercontent.com/1410282/206746604-b5f7da98-5223-442b-a74f-7df7988d95ec.png">

As a result, after reloading/logging, you get a gazillion errors and have no idea what happened.

If at some point it occurs to you that your sudden problem may be related to that option, and you disable now this option and reload with your set, you are making things not better: Since these Blizz addons are likely not part of any of your sets, loading a set will not enable them.

Also clicking 'Enable All' will not help you, as SAM's 'Disable All' / 'Enable All' seems to act on _displayed_ addons (not on _all_ addons as the button label suggests).

To get your disabled Blizz addons back, you have to re-enable the option, _then_ click 'Enable All', and then you can disable the option for good and reload with your set.

Well, once you have learned that, it's no longer an issue, but it can take a while to figure this out ;-)

I think a good solution would be to hard-exclude all Blizz addons from being disabled. Or popping up a fat warning if someone curious like me enables the option ;)

– Tom

**Comment by Eliote** [comment]
This feature is kind of an (happy?) accident. (Blizzards addons just showed up when I made the algorithm for build the dependency tree)
I added a warning and made the "enable/disable all" buttons ignore then, for now is probably enough. :)

**Comment by tflo** [comment]
Very nice warning text!

Too late for me, but you've saved thousands of other users from the traumatic experience when suddenly the entire UI freaks out and you don't know why… 😇
