### ISSUE TITLE
Feature Request:  LDB Add Selectable list of Profiles

### ISSUE THREAD

**Issue by fireymerlin** [Eliote/SimpleAddonManager#24]
Change your data broker (LDB) to show a clickable list similar to this picture which would allow selection of profiles to load.  
Clicking on a profile name would run "/sam profile NAME" and present a popup.

Just a suggestion.

![image](https://user-images.githubusercontent.com/441778/206906234-16d7d0b1-2398-408a-85f8-ef814eaf2843.png)

![image](https://user-images.githubusercontent.com/441778/206906277-ede37210-40c4-4215-a26f-e6c57e1423cf.png)

**Comment by fireymerlin** [comment]
I just saw the profile dependencies so I don't know if the Enabled column and the click/RichClick would be needed.  Just a list of profiles that could be clicked to enable.

**Comment by fireymerlin** [comment]
I reworked the mockup and included the /sam profile DBM   results
![image](https://user-images.githubusercontent.com/441778/206905471-7c409d99-d9ca-425f-ae84-6ebcc54a600a.png)

![image](https://user-images.githubusercontent.com/441778/206905490-f4ef497a-c2ed-4066-8203-10c7bd80df8e.png)

**Comment by Eliote** [comment]
Done in c0ba1767.
