### ISSUE TITLE
Two (minor) suggestions for custom categories

### ISSUE THREAD

**Issue by tflo** [Eliote/SimpleAddonManager#25]
## Assign category recursively

Would be great to have the possibility to assign a custom category recursively to all dependencies, instead of having to right-click each one.

For example, for things like this:

<details>
<summary>Screenshot</summary>
<img width="658" alt="WoWScrnShot_121322_142023" src="https://user-images.githubusercontent.com/1410282/207329714-5e1121fe-914b-4d86-9c10-e22ccf438e97.png">
</details>

This could be done, for example, via modifier key: If I assign the category "Map" via context menu to the top-level item ("HandyNotes") _while holding down the Shift key_, "Maps" would be assigned _– additively –_ to all its children. 

The same for removing a category assignment.

## Showing custom categories in tooltip

Would be useful mainly in the category setup process, to quickly see, without right-clicking, if I have applied the category. (But also later for certain addons, where the description is so poor that you have no clue what this thing was for ;)

Like this:

<img width="328" alt="WoWScrnShot_121322_125135" src="https://user-images.githubusercontent.com/1410282/207316044-b1968f60-ece1-4eac-97ad-665f0f7915b7.png">

***

Thanks for considering,

– Tom

***

Edit: Replaced example image for recursive categories with a better one.

**Comment by kblair210** [comment]
Upvote on this suggestion. HandyNotes in particular is seriously annoying to check through, but there are others also.

**Comment by tflo** [comment]
Thank you for both!
