### ISSUE TITLE
Feature Request: Show character addons only

### ISSUE THREAD

**Issue by Iowerth** [Eliote/SimpleAddonManager#31]
Hi. Please add option when showing addons list will always show for current character only. It is implemented in LeatrixPlus and it is very useful.
When I installed your addon, I got this option disappeared and it is become very usefulness.
How it look in LeatrixPlus:
```lua
if LeaPlusLC["CharAddonList"] == "On" then
	-- Set the addon list to character by default
	if AddonCharacterDropDown and AddonCharacterDropDown.selectedValue then
		AddonCharacterDropDown.selectedValue = UnitName("player");
		AddonCharacterDropDownText:SetText(UnitName("player"))
	end
end
```

**Comment by wheatbread** [comment]
If it helps, tflo posted a way you can edit the lua yourself to make it default to character addons.  Near the bottom of this post: https://github.com/Eliote/SimpleAddonManager/issues/33#issuecomment-1804475690

**Comment by Iowerth** [comment]
@wheatbread perfect! Thank you very much!

**Comment by Eliote** [comment]
With f879545f442ec6b90412f6e240889d6d547e3c1d, the UI should remember the selected option.
