### ISSUE TITLE
complete broken in 10.2

### ISSUE THREAD

**Issue by Squimbert** [Eliote/SimpleAddonManager#33]
title

**Comment by jrosco** [comment]
I'm seeing this error 
```
27x bad argument #1 to '?' (Usage: C_AddOns.DisableAllAddOns([character]))
[string "=[C]"]: in function `DisableAllAddOns'
[string "@SimpleAddonManager/Core.lua"]:346: in function `DisableAllAddOns'
[string "@SimpleAddonManager/Profile.lua"]:99: in function `LoadAddonsFromProfile'
[string "@SimpleAddonManager/Profile.lua"]:283: in function `OnAccept'
[string "@FrameXML/StaticPopup.lua"]:5317: in function `StaticPopup_OnClick'
[string "*StaticPopup.xml:24_OnClick"]:1: in function <[string "*StaticPopup.xml:24_OnClick"]:1>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: C_AddOns.DisableAllAddOns([character]))"
```

**Comment by tflo** [comment]
This change lets you use the addon until it gets properly fixed (Core.lua, first change at line 331):

```diff
diff --git a/SimpleAddonManager/Core.lua b/SimpleAddonManager/Core.lua
--- a/SimpleAddonManager/Core.lua
+++ b/SimpleAddonManager/Core.lua
@@ -322,34 +322,34 @@
 end
 
 function frame:IsAddonInstalled(indexOrName)
 	local _, _, _, _, reason = GetAddOnInfo(indexOrName)
 	return reason ~= "MISSING"
 end
 
 function frame:EnableAddOn(indexOrName)
 	local c = frame:GetCharacter()
-	EnableAddOn(indexOrName, c)
+	EnableAddOn(indexOrName)
 end
 
 function frame:DisableAddOn(indexOrName)
 	local c = frame:GetCharacter()
-	DisableAddOn(indexOrName, c)
+	DisableAddOn(indexOrName)
 end
 
 function frame:EnableAllAddOns()
 	local c = frame:GetCharacter()
-	EnableAllAddOns(c)
+	EnableAllAddOns()
 end
 
 function frame:DisableAllAddOns()
 	local c = frame:GetCharacter()
-	DisableAllAddOns(c)
+	DisableAllAddOns()
 end
 
 local GetAddOnMetadata = C_AddOns and C_AddOns.GetAddOnMetadata or GetAddOnMetadata
 function frame:GetAddOnMetadata(addon, field)
 	return GetAddOnMetadata(addon, field)
 end
 
 -- When entering/leaving lfg, realm returns nil. Cache to avoid errors.
 local nameCache, realmCache, classColor
```

In short: 4× remove the `c` argument.

**This is a workaround, not a fix!**

**Comment by Eliote** [comment]
Blizzard moved a bunch of AddOn related APIs to `C_AddOn`. I'll try to fix it by this weekend.

**Comment by tflo** [comment]
> Blizzard moved a bunch of AddOn related APIs to C_AddOn

I think that's not the issue, because they put aliases in their [Deprecated_10_2_0.lua](https://github.com/Gethe/wow-ui-source/blob/ptr2/Interface/AddOns/Blizzard_Deprecated/Deprecated_10_2_0.lua).

But it seems these Disable/EnableAddOn functions now expect a string (not a boolean): https://github.com/Gethe/wow-ui-source/compare/10.1.7..10.2.0#diff-3b13eb1f91030308f796ca6c0b172b9adcc1080a80283e55f953dee04e865783

**Comment by Eliote** [comment]
I'm pretty sure those alias only work in beta.

**Comment by tflo** [comment]
They definitively work in the current live version, because I have also (still) some of the old ones in my addons.

And the modification above works also (without C_AddOns).

**Comment by Eliote** [comment]
Apparently they also inverted the parameters in some functions (`character, index` become `index, character`), and a bunch of places that expected `true` for all characters now expects `nil`. This will be FUN to fix. 😅

**Comment by tflo** [comment]
> This will be FUN to fix. 😅

Yes, that's what I thought too… ;)

**Comment by JourneyOver** [comment]
> Apparently they also inverted the parameters in some functions (`character, index` become `index, character`), and a bunch of places that expected `true` for all characters now expects `nil`. This will be FUN to fix. 😅

Could this be a reason on why if I have an addon disabled on one toon I need to end up now putting the `addonname: enabled` into the `addons.txt` file for any toons I actually want it enabled on now as before 10.2 I could just have `addonname: disabled` only in the `addons.txt` for the toon I wanted the addon disabled on while leaving it enabled for any other toons but as of 10.2 it seems that if `addonname: enabled` is missing for any toons the addon ends up being disabled anyways.

**Comment by tflo** [comment]
> Before 10.2, I could simply have addonname: disabled only in the addons.txt for the character […]

Interesting. I noticed some weirdness already before 10.2 (started a few weeks ago): Sometimes the supposedly active addon sets of my other toons seem to get messed up, i.e. it's not the same as it was when I logged out on the other toon.

I still don't know what's causing this, and I didn't investigate further because I remembered seeing this somewhere in the past, maybe a year or more ago. Back then it just went away with a server restart (so it was a Blizz bug). But maybe it's something different right now.

**Comment by tflo** [comment]
Here is a probably better variant of the workaround. Instead of crudely applying all changes to all toons, it should respect the character dropdown menu (All vs Char) again:

```diff
diff --git a/SimpleAddonManager/Core.lua b/SimpleAddonManager/Core.lua
--- a/SimpleAddonManager/Core.lua
+++ b/SimpleAddonManager/Core.lua
@@ -329,19 +329,23 @@
 function frame:EnableAddOn(indexOrName)
 	local c = frame:GetCharacter()
+	if type(c) ~= 'string' then c = nil end
 	EnableAddOn(indexOrName, c)
 end
 
 function frame:DisableAddOn(indexOrName)
 	local c = frame:GetCharacter()
+	if type(c) ~= 'string' then c = nil end
 	DisableAddOn(indexOrName, c)
 end
 
 function frame:EnableAllAddOns()
 	local c = frame:GetCharacter()
+	if type(c) ~= 'string' then c = nil end
 	EnableAllAddOns(c)
 end
 
 function frame:DisableAllAddOns()
 	local c = frame:GetCharacter()
+	if type(c) ~= 'string' then c = nil end
 	DisableAllAddOns(c)
 end
```

This is instead of the first variant, not additionally.

**Comment by Soromeister** [comment]
Can someone help out with some guides on how to apply these diff results? Is there some tool that can do this if I save the output (minus the line that starts with `diff --git ...`) so that the changes can be applied programmatically? I am not used to working with diff outputs or diff/patch files.

**Comment by tflo** [comment]
> how to apply these diff results? 

Sure. 

1. First, use a _text editor_ (e.g. Notepad++ on Windows, BBEdit on Mac) to edit files, ideally one that displays the line numbers. Do _not_ use a word processor (like MS Word etc.).

2. At the top of each diff you see the file name and path, e.g. SimpleAddonManager/Core.lua. That's the file you have to edit (inside the addon folder in your active WoW `AddOns` directory).

3. The "@" numbers (e.g. `@@ -329,19 +329,23 @@`) show you the line where the diff starts (line 329 in the example). Go there. You should now see the code part that is displayed in the diff. Now simply remove all red lines (also marked with a minus sign) and add the green lines (plus sign).
  - If there aren't red lines (like in the 2nd version of the workaround), just add the green lines.
  - Correct indentation is not crucial, line breaks are crucial.

4. Visually compare your code against the diff to check if you have implemented all changes, and save the file with the same extension it had before (usually lua or xml).

To do it programmatically, you have to use any program that can apply "patch files" to another file. But I think it's not worth it here, as the changes are minuscule. And I'm not sure if the diffs as I have posted them are patch-compatible.

**Comment by Soromeister** [comment]
Thanks @tflo for the detailed explanation. Point 3 is what I was actually looking for. I assumed that the example `@@ -329,19 +329,23 @@` means line 329, column 19 but just wanted to confirm, which you did.

**Comment by tflo** [comment]
> means line 329, column 19 

The second number is the count of lines (1st one is before, 2nd one is after) of the whole displayed chunk of code.

For a better explanation, go [here](https://unix.stackexchange.com/questions/480443/how-shall-i-understand-the-unified-format-of-diff-output).

**Comment by Eliote** [comment]
Should be fixed by 3635d9a6. ([releases/v1.23](https://github.com/Eliote/SimpleAddonManager/releases/tag/v1.23))

**Comment by tflo** [comment]
Thank you!

And with addon icons now 😍

**Comment by tflo** [comment]
Wow, v1.26 is even _more_ better 🤩 The addon is approaching the state of perfection…

Huge extra thanks for saving the Character-vs-All setting in the DB – and globally for all toons! (I was planning on creating a request this, or for a flat login default to \<charname\> ;)
