### ISSUE TITLE
LUA errors [TWW Beta]

### ISSUE THREAD

**Issue by tnwn** [Eliote/SimpleAddonManager#40]
Fresh install of beta client. Only installed addon.

**LUA 1/3**
Message: Interface/AddOns/SimpleAddonManager/Core.lua:448: attempt to index global 'GameMenuButtonAddons' (a nil value)
Time: Sun Jun  9 13:30:40 2024
Count: 1
Stack: Interface/AddOns/SimpleAddonManager/Core.lua:448: attempt to index global 'GameMenuButtonAddons' (a nil value)
[string "@Interface/AddOns/SimpleAddonManager/Core.lua"]:448: in function <Interface/AddOns/SimpleAddonManager/Core.lua:447>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:482: in function `SetUIPanel'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:289: in function `ShowUIPanel'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:168: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:163>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:860: in function `ShowUIPanel'
[string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:2860: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals: (*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'GameMenuButtonAddons' (a nil value)"
frame = SimpleAddonManager {
 compat = <table> {
 }
 Inset = SimpleAddonManagerInset {
 }
 CATEGORY_SIZE_W = 250
 TitleContainer = Frame {
 }
 MIN_SIZE_W = 470
 Bg = SimpleAddonManagerBg {
 }
 NineSlice = Frame {
 }
 isMenuHooked = true
 MIN_SIZE_H = 400
 layoutType = "PortraitFrameTemplate"
 PortraitContainer = Frame {
 }
 TopTileStreaks = Texture {
 }
 CloseButton = SimpleAddonManagerCloseButton {
 }
}

**LUA 2/3**
Message: ...bs/ElioteDropDownMenu-1.0/ElioteDropDownMenu-1.0.lua:1836: attempt to call global 'GetMouseFocus' (a nil value)
Time: Sun Jun  9 13:33:27 2024
Count: 15
Stack: ...bs/ElioteDropDownMenu-1.0/ElioteDropDownMenu-1.0.lua:1836: attempt to call global 'GetMouseFocus' (a nil value)
[string "@Interface/AddOns/SimpleAddonManager/Libs/ElioteDropDownMenu-1.0/ElioteDropDownMenu-1.0.lua"]:1836: in function <...bs/ElioteDropDownMenu-1.0/ElioteDropDownMenu-1.0.lua:1835>

Locals: self = Frame {
}
event = "GLOBAL_MOUSE_DOWN"
buttonID = "LeftButton"
(*temporary) = nil
(*temporary) = "attempt to call global 'GetMouseFocus' (a nil value)"
lib = <table> {
 UIDROPDOWNMENU_MENU_LEVEL = 1
 UIDROPDOWNMENU_BORDER_HEIGHT = 15
 HandlesGlobalMouseEventMixin = <table> {
 }
 UIDROPDOWNMENU_SHOW_TIME = 2
 OPEN_DROPDOWNMENUS = <table> {
 }
 UIDROPDOWNMENU_BUTTON_HEIGHT = 16
 UIDROPDOWNMENU_DEFAULT_TEXT_HEIGHT = 10
 UIDROPDOWNMENU_MAXBUTTONS = 1
 UIDROPDOWNMENU_MAXLEVELS = 2
 UIDROPDOWNMENU_DISPLAY_MODE_MENU_CHECKBOX_OFFSET = 2
}

**LUA 3/3**
Message: Interface/AddOns/SimpleAddonManager/Core.lua:448: attempt to index global 'GameMenuButtonAddons' (a nil value)
Time: Sun Jun  9 13:30:50 2024
Count: 1
Stack: Interface/AddOns/SimpleAddonManager/Core.lua:448: attempt to index global 'GameMenuButtonAddons' (a nil value)
[string "@Interface/AddOns/SimpleAddonManager/Core.lua"]:448: in function <Interface/AddOns/SimpleAddonManager/Core.lua:447>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:482: in function `SetUIPanel'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:289: in function `ShowUIPanel'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:168: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:163>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:860: in function `ShowUIPanel'
[string "@Interface/AddOns/Blizzard_GameMenu/Standard/GameMenuFrame.lua"]:57: in function <.../AddOns/Blizzard_GameMenu/Standard/GameMenuFrame.lua:55>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...e/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:513: in function `HideUIPanel'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:172: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:163>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:880: in function `HideUIPanel'
[string "@Interface/AddOns/Blizzard_SharedXML/Mainline/SharedUIPanelTemplates.lua"]:154: in function <...izzard_SharedXML/Mainline/SharedUIPanelTemplates.lua:145>

Locals: (*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'GameMenuButtonAddons' (a nil value)"
frame = SimpleAddonManager {
 compat = <table> {
 }
 Inset = SimpleAddonManagerInset {
 }
 CATEGORY_SIZE_W = 250
 TitleContainer = Frame {
 }
 MIN_SIZE_W = 470
 Bg = SimpleAddonManagerBg {
 }
 NineSlice = Frame {
 }
 isMenuHooked = true
 MIN_SIZE_H = 400
 layoutType = "PortraitFrameTemplate"
 PortraitContainer = Frame {
 }
 TopTileStreaks = Texture {
 }
 CloseButton = SimpleAddonManagerCloseButton {
 }
}

**Comment by Eliote** [comment]
I don't have access to the beta. :(

**Comment by tnwn** [comment]
Ok, tell me if you want me to test something on the beta client :)

**Comment by Eliote** [comment]
Should be fixed by 22d8ccba0eabb26e871cf95a6db3aa84b28db857 and a828407d2484d05227bbfb40614adf6de42cb72b
