### ISSUE TITLE
Add/Remove selected addons to category (question/request)

### ISSUE THREAD

**Issue by Boatshoes24** [Eliote/SimpleAddonManager#42]
Is there a way to mass add addons to a category? Right clicking each addon (especially for things like bigwigs with lots of dependents) can be very tedious vs being able to mass add addons to a category by just what is/isn't checked or something.

**Comment by Eliote** [comment]
Yes, when you use the search, a little button will appear to the right of the search bar with some options.
![image](https://github.com/user-attachments/assets/2a6f7deb-e0ad-4bd3-ad32-01715e3e1fe0)
