### ISSUE TITLE
[suggestion] Add other chars to the char selection dropdown

### ISSUE THREAD

**Issue by tflo** [Eliote/SimpleAddonManager#44]
Since 11.0.5.57171 we have [an acknowledged Blizzard Bug (apparently only on macOS)](https://eu.forums.blizzard.com/en/wow/t/mac-game-is-not-opening-after-patch/544750/33) that prevents the game from remembering the addon enabled/disabled states of every char when you launch or exit the game (all addons become enabled and are written as such to *AddOns.txt*).

SAM is already a *huge* help here (and of course I recommended it in the linked bug thread 😇), as I can quickly load a set for all chars when I’m logged into my first toon after game relaunch.

However, it would be even greater if I could select individual other toons from the dropdown menu instead of just “All” and “\<current char\>“ (like with the Blizz addon manager). [^1]

For obvious reasons, this feature would be *super* useful in the context of the current Blizz bug, but I think it would still be useful in general too.[^2] (Somehow I think to remember that SAM did have this feature in the beginning, but probably I’m confusing it with some other addon manager.)

[^1]: The menu would be empty at the beginning and become populated with the other toons’ names as I login to the other toons.

[^2]: In case you implement it, just make sure please that “All” and “\<current char\>“ remain positioned at the top of the list and that it defaults to \<current char\>.

**Comment by Eliote** [comment]
As far as I know this can only be done in the glue screen. At least the last time I tested, sending any character other than the current one to the API did nothing.

**Comment by tflo** [comment]
I just tried both, while logged in, and both work fine. E.g.:

```
C_AddOns.DisableAddOn('SavedInstances', 'Llynis')
C_AddOns.EnableAddOn('VolumeTooltip', 'Llynis')
```

`Llynis` is the name of an arbitrary alt (not the one logged in, of course). _Note the absence of the realm name._ 

Logging in to “Llynis” revealed that “SavedInstances” was disabled (it was enabled before), and “ VolumeTooltip” was enabled (it was disabled on all toons before).

**Comment by Eliote** [comment]
That's cool! I think when I tested it we still had that bug where the "all" option didn't work, maybe that's why it also didn't work.

**Comment by tflo** [comment]
OK, [Blizz fixed their all-addons-enabled bug](https://eu.forums.blizzard.com/en/wow/t/mac-game-is-not-opening-after-patch/544750/47) with 11.0.5.57292, so this is no longer needed.

Just joking. Judging by your reaction…

> That's cool!

…it seems you also find this feature useful. Happy to hear that 😊

**Comment by tflo** [comment]
Thank you!
